In [1]:
import numpy as np

In [2]:
A = np.array([[-0.03, 0.06],
              [0.03, -0.06]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

eigenvalues, eigenvectors

(array([ 0.  , -0.09]),
 array([[ 0.89442719, -0.70710678],
        [ 0.4472136 ,  0.70710678]]))

In [7]:
initial_conditions = np.array([[300], [0]])

y_0 = np.linalg.inv(eigenvectors) @ initial_conditions

y_0

array([[ 223.60679775],
       [-141.42135624]])